version: '3.1'
services:
  server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      GCLIENTID: ${GCLIENTID}
      GCLIENTSECRET: ${GCLIENTSECRET}
      GCBURL: ${GCBURL}
      DBHOST: ${DBHOST}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DBPORT: ${DBPORT}
      PORT: ${PORT}
      REDISHOST: redis
      REDISPORT: 6379
    volumes:
      - "./src:/app/src"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    restart: always
    volumes:
      - rdata:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
  rdata: