FROM mhart/alpine-node:8

COPY package.json /app/
COPY ormconfig.docker.js /app/ormconfig.js
COPY tsconfig.json /app/
COPY tslint.json /app/
COPY initial_data /app/initial_data


COPY client/build /app/client

RUN cd /app && \
    npm install --quiet
WORKDIR /app

CMD npm run dev